; PlatformIO Project Configuration File
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    zinggjm/GxEPD2@^1.5.0
    adafruit/Adafruit GFX Library @ ^1.11.9
; PSRAM/16MB config removed — not needed for 2.9" display (5KB buffer)
; Re-add when upgrading to 7.5" display
